import { useMemo, useState } from "react";
import { DOMAIN_ORDER } from "../styles/tokens";
import { UPGRADE_URL, PERSONALIZED_VOICE_LABEL, PRODUCT_NAME } from "../config/branding";
import DomainSection from "./DomainSection";
import DomainSectionTeaser from "./DomainSectionTeaser";
import NextActionSpotlight from "./NextActionSpotlight";
import BusinessTeaser from "./BusinessTeaser";
import DigitalTeaser from "./DigitalTeaser";
import PersonalizedTeaser from "./PersonalizedTeaser";
import UpgradeButton from "./UpgradeButton";
import ChatWidget from "./ChatWidget";
import ProgressBar from "./ProgressBar";
import ActionItemRow from "./ActionItemRow";

function groupByDomain(items) {
  const groups = {};
  DOMAIN_ORDER.forEach((d) => { groups[d] = []; });
  const other = [];
  items.forEach((item) => {
    if (item.domain && groups[item.domain]) groups[item.domain].push(item);
    else other.push(item);
  });
  return { groups, other };
}

function downloadPlan(user, result) {
  const { plan, personalized } = result;
  const lines = [
    "MY FINAL PLAYBOOK",
    "=================",
    `Name: ${user.name}`,
    plan.leadProfile ? `Situation: ${plan.leadProfile.name}` : "",
    "",
    "ACTION ITEMS",
    "------------",
    ...plan.actionItems.map((a, i) => {
      const p = [`${i + 1}. [${(a.domain || "other").toUpperCase()}] ${a.text}`];
      if (a.script) p.push(`   Say: "${a.script}"`);
      return p.join("\n");
    }),
  ];
  if (plan.businessActionItems?.length > 0) {
    lines.push("", "BUSINESS PLANNING", "-----------------");
    lines.push(...plan.businessActionItems.map((a, i) => `${i + 1}. [${(a.domain || "other").toUpperCase()}] ${a.text}`));
  }
  if (plan.digitalActionItems?.length > 0) {
    lines.push("", "DIGITAL PLANNING", "----------------");
    lines.push(...plan.digitalActionItems.map((a, i) => {
      const p = [`${i + 1}. ${a.text}`];
      if (a.script) p.push(`   Say: "${a.script}"`);
      return p.join("\n");
    }));
  }
  if (personalized) {
    lines.push("", "YOUR NEXT 30 DAYS", "-----------------", personalized.headline, "");
    personalized.steps.forEach((s, i) => {
      lines.push(`${i + 1}. ${s.step}`);
      lines.push(`   ${s.why_it_matters}`);
      if (s.script) lines.push(`   Say: "${s.script}"`);
    });
    lines.push("", personalized.closing_note);
  }
  lines.push("", `Generated by ${PRODUCT_NAME}`);

  const blob = new Blob([lines.filter(Boolean).join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `final-playbook-${user.name.toLowerCase()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ResultsPanel({ user, account, result, onUpgrade, onRestart }) {
  const [doneSet, setDoneSet] = useState(new Set());
  const { plan, personalized } = result;
  // Paid features light up based on the live server entitlement (account.tier),
  // falling back to the result's own tier if account isn't loaded.
  const isPaid = (account?.tier || result.tier || user.tier) === "paid";

  // plan.actionItems is already priority-ordered and capped by
  // rules_engine.build_plan() -- the first item IS the member's top priority,
  // no extra sorting needed here.
  const [nextItem, ...restItems] = plan.actionItems || [];

  const { groups } = useMemo(() => groupByDomain(plan.actionItems || []), [plan.actionItems]);
  // Teaser lists exclude the already-spotlighted nextItem so it isn't shown
  // twice (once full, once blurred).
  const teaserGroups = useMemo(() => {
    if (!nextItem) return groups;
    const filtered = {};
    DOMAIN_ORDER.forEach((d) => {
      filtered[d] = groups[d].filter((item) => item.text !== nextItem.text);
    });
    return filtered;
  }, [groups, nextItem]);

  const business = useMemo(() => groupByDomain(plan.businessActionItems || []), [plan.businessActionItems]);
  const allItems = [
    ...(plan.actionItems || []),
    ...(plan.businessActionItems || []),
    ...(plan.digitalActionItems || []),
  ];

  function toggleItem(text) {
    setDoneSet((prev) => {
      const next = new Set(prev);
      if (next.has(text)) next.delete(text);
      else next.add(text);
      return next;
    });
  }

  function openUpgrade() {
    if (onUpgrade) onUpgrade();
    else window.open(UPGRADE_URL, "_blank", "noopener,noreferrer");
  }

  if (!plan.leadProfile) {
    return (
      <div className="fp-page">
        <p className="fp-body">
          Based on what you shared, nothing specific matched yet, that can happen with a light answer set.
          Try going back and adding a bit more detail.
        </p>
        <button onClick={onRestart} className="fp-btn">Start over</button>
      </div>
    );
  }

  return (
    <div className="fp-page-wide">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 }}>
        <div>
          <p className="fp-question-topic">Your matched situation</p>
          <h2 className="fp-h2">{plan.leadProfile.name}</h2>
        </div>
        <button onClick={onRestart} className="fp-btn-secondary">Start over</button>
      </div>

      {isPaid && <ProgressBar doneCount={doneSet.size} totalCount={allItems.length} />}

      <NextActionSpotlight item={nextItem} isPaid={isPaid} totalItemCount={allItems.length} />

      {isPaid ? (
        DOMAIN_ORDER.map((d) => (
          <DomainSection key={d} domainKey={d} items={groups[d]} doneSet={doneSet} onToggleItem={toggleItem} />
        ))
      ) : (
        DOMAIN_ORDER.map((d) => (
          <DomainSectionTeaser key={d} domainKey={d} items={teaserGroups[d]} onUpgradeClick={openUpgrade} />
        ))
      )}

      {isPaid && plan.businessActionItems?.length > 0 && (
        <>
          <p className="fp-question-topic" style={{ marginTop: 28 }}>Business planning (separate checklist)</p>
          {DOMAIN_ORDER.map((d) => (
            <DomainSection key={`biz-${d}`} domainKey={d} items={business.groups[d]} doneSet={doneSet} onToggleItem={toggleItem} />
          ))}
        </>
      )}
      {!isPaid && <BusinessTeaser count={plan.businessActionItems?.length || 0} />}

      {isPaid && plan.digitalActionItems?.length > 0 && (
        <>
          <p className="fp-question-topic" style={{ marginTop: 28 }}>Digital planning (separate checklist)</p>
          <div className="fp-domain-section" style={{ borderLeftColor: "var(--brand)" }}>
            {plan.digitalActionItems.map((item) => (
              <ActionItemRow
                key={item.text}
                item={item}
                done={doneSet.has(item.text)}
                onToggle={() => toggleItem(item.text)}
              />
            ))}
          </div>
        </>
      )}
      {!isPaid && <DigitalTeaser count={plan.digitalActionItems?.length || 0} />}

      {plan.quotes?.map((q, i) => (
        <p key={i} className="fp-quote-block">"{q}"</p>
      ))}

      {isPaid && personalized && (
        <div className="fp-personalized">
          <p className="fp-question-topic">Your next 3 days, personalized for you</p>
          <h3 style={{ margin: "0 0 12px" }}>{personalized.headline}</h3>
          {personalized.steps.map((s, i) => (
            <div key={i} style={{ marginBottom: 12 }}>
              <p className="fp-item-text" style={{ fontWeight: 600 }}>{s.step}</p>
              <p className="fp-dim">{s.why_it_matters}</p>
              {s.script && <p className="fp-item-script">"{s.script}"</p>}
            </div>
          ))}
          <p className="fp-body" style={{ marginTop: 12, marginBottom: 0 }}>{personalized.closing_note}</p>
        </div>
      )}
      {!isPaid && <PersonalizedTeaser />}

      {isPaid ? (
        <button onClick={() => downloadPlan(user, result)} className="fp-btn" style={{ marginTop: 24 }}>
          Download my playbook ↓
        </button>
      ) : (
        <UpgradeButton className="fp-btn-upgrade" style={{ marginTop: 24, width: "100%" }}>
          Unlock my full playbook →
        </UpgradeButton>
      )}

      <ChatWidget plan={plan} memberFirstName={user.name} tier={user.tier} />
    </div>
  );
}
